name: kdb
channels:
  - kx
  - conda-forge
  - https://10.0.1.221/home/jack/build/conda-channel
dependencies:
  - boto3
  - kdb
  - kdb-core
  - kdb-eventbus
  - kdb-pubsub
  - kdb-rdb
  - numpy
  - pandas
  - psutil
  - pyq
  - python=3.7
  - pyyaml
  - traitlets
  - yaml
