#!/bin/bash

# construct PS1
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

construct_ps1() {
    ### configure color for different envs
    ## Colors
    # 30 - Black
    # 31 - Red
    # 32 - Green
    # 33 - Yellow
    # 34 - Blue
    # 35 - Purple
    # 36 - Cyan
    # 37 - White
    # 90 - Dark Gray
    # 91 - Light Red
    # 92 - Light Green
    # 93 - Light Yellow
    # 94 - Light Blue
    # 95 - Light Purple
    # 96 - Light Cyan
    # 97 - White

    LOCAL_HOSTNAME=$(hostname -d)
    if [[ $LOCAL_HOSTNAME == "nomura.com" ]]; then
        COLOR="\[\e[0;32m\]"    # dark green
    else
        COLOR="\[\e[0;91m\]"    # light red
    fi

    GRAY="\[\e[0;37m\]"
    YELLOW="\[\e[0;93m\]"
    # "user@host:pwd (git branch) $ "
    echo "${COLOR}\u${GRAY}@${COLOR}\H${GRAY}:${COLOR}\w${YELLOW}\$(parse_git_branch) ${GRAY}$ "
}

export PS1=$(construct_ps1)

# fix wsl directory colors
export LS_COLORS='ow=01;34;01'
