
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
  }

alias aa=". ~/anaconda3/etc/profile.d/conda.sh; conda activate"

alias q="rlwrap q"
alias p="python3"

alias l="ls -CF"
alias ls="ls -h --color=auto"
alias la="ls -la --color=auto"
alias ll="ls -l --color=auto"
