alias aa=". /home/jack/miniconda/etc/profile.d/conda.sh; conda activate"

alias q="rlwrap q"
alias p="rlwrap python3"

alias l="ls -CF"
alias ls="ls -h --color=auto"
alias la="ls -la --color=auto"
alias ll="ls -l --color=auto"

alias ssh="ssh -o StrictHostKeyChecking=no"

source $HOME/repos/environments-setup/util/git-funcs.sh

alias qeb="qstart --app eventbus --proctype "
alias qgw="qstart --app gateway --proctype "
alias qhdb="qstart --app hdb --proctype "
alias qrdb="qstart --app rdb --proctype "
