#!/bin/bash

# construct PS1
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
  }

## Colors
# 30 - Black
# 31 - Red
# 32 - Green
# 33 - Yellow
# 34 - Blue
# 35 - Purple
# 36 - Cyan
# 37 - White

construct_ps1(){
    # configure color for different envs
    LOCAL_HOSTNAME=$(hostname -d)
    if [[ $LOCAL_HOSTNAME == "localdomain" ]]; then
        SYSNAME="(wsl)"
        COLOR="35m"
    else
        SYSNAME="(aws)"
        COLOR="31m"
    fi
    # setup command prompt
    USERNAME="\[\e[01;"$COLOR"\]\u"
    HOST="\[\e[01;"$COLOR"\]\H"
    DIR="\[\e[01;32m\]\w"
    GIT="\[\e[01;36m\]\$(parse_git_branch)"
    END="\[\e[01;37m\]$ "
    NEW_LINE="\n\[\e[01;37m\] >>> \[\e[01;00m\]"
    # join parts
    echo "$USERNAME\[\e[01;37m\]@$HOST$\[\e[01;37m\]: $DIR$GIT $END"
}

export PS1=$(construct_ps1)

# fix wsl directory colors
export LS_COLORS='ow=01;34;01'

# Dev envvars
export MINICONDAHOME=$HOME/miniconda
export REPOS=$HOME/repos
export BUILDDIR=$HOME/build
export CORECHANNEL=$BUILDDIR/conda-channel
export notes=$REPOS/notes

export KDBSCHEMA=$REPOS/kdb-schema
export PYTHONPATH=$REPOS/kdb-core/python
export COREHOME=$REPOS/kdb-core
export EBHOME=$REPOS/kdb-eventbus
export RDBHOME=$REPOS/kdb-rdb
