#!/bin/bash

for bash_file in .bashrc .bash_aliases .bash_envvars
do
    if [ -f $HOME/$bash_file ]; then
        source $HOME/$bash_file
    fi
done

# if on aws
if [[ $(hostname -d) != "localdomain" ]]; then
    export INSTANCEID=$(ec2metadata --instance-id)
fi
