alias aa=". ~/miniconda/etc/profile.d/conda.sh; conda activate"

alias q="rlwrap q"
alias p="rlwrap python3"

alias l="ls -CF"
alias ls="ls -h --color=auto"
alias la="ls -la --color=auto"
alias ll="ls -l --color=auto"

alias cdpre='cd $CONDA_PREFIX'
alias cdq='cd $CONDA_PREFIX/q'
alias cdsrc='cd $CONDA_PREFIX/q/src'
